services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432
    env_file:
      - db.env

  storage:
    image: quay.io/minio/minio

    ports:
      - 9000:9000
      - 9090:9090
    
    volumes:
      - storage:/data
    
    env_file:
      - storage.env

    command: server /data --console-address ":9090"

volumes:
  db:
  storage: